Default: &defaults
  user: ostoslista
  password: ostoslista
  host: localhost
  port: 5432
  database: ostoslista
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: ostoslista_test
  <<: *defaults

Staging:
  database: ostoslista_staging
  poolsize: 100
  <<: *defaults

Production:
  database: ostoslista_production
  poolsize: 100
  <<: *defaults
